import { PortalIconCatalogItem } from './portal-icon-catalog.types';

/** Vista previa en el ERP (emoji representativo; el portal usa iconos vectoriales). */
export const PORTAL_ICON_PREVIEW_EMOJI: Record<string, string> = {
  'academic-cap': '🎓',
  phone: '📞',
  'map-pin': '📍',
  computer: '💻',
  'computer-desktop': '💻',
  'chart-bar': '📊',
  'check-badge': '✅',
  'device-mobile': '📱',
  'trending-up': '📈',
  bicycle: '🏍️',
  car: '🚗',
  bus: '🚌',
  truck: '🚛',
  'shield-check': '🛡️',
  wrench: '🔧',
  lifebuoy: '⛑️',
  clipboard: '📋',
  document: '📄',
  book: '📚',
  bell: '🔔',
  trophy: '🏅',
  heart: '💚',
  globe: '🌍',
  building: '🏫',
  envelope: '✉️',
  chat: '💬',
  star: '⭐',
  'light-bulb': '💡',
  exclamation: '⚠️',
  'magnifying-glass': '🔍',
  flag: '🇨🇴',
  bolt: '💪',
  eye: '👁️',
  'hand-raised': '👉',
  sun: '⛺',
  signal: '🚦',
  users: '👥',
  'user-circle': '👤',
  'user-group': '🤝',
  presentation: '📊',
  newspaper: '📰',
  'qr-code': '▣',
  identification: '🪪',
  inbox: '📥',
  tablet: '📱',
  home: '🏠',
  beaker: '🧪',
  fire: '🔥',
  stop: '🛑',
  minus: '−',
  plus: '+',
  'check-circle': '🎯',
  'arrow-right': '→',
  'download-tray': '⬇️',
  sparkles: '✦',
  android: '📱',
  download: '📈',
  certificate: '📜',
  award: '🏆',
  target: '🎯',
  camp: '⛺',
  visibility: '👁️',
  mechanic: '🔧',
  defensive: '🛡️',
  'first-aid': '⛑️',
  pqr: '📋',
  suggestion: '💡',
  complaint: '⚠️',
  petition: '🔔',
  compliment: '⭐',
};

type BuiltinSeed = { slug: string; label: string; category: string; preview?: string };

const BUILTIN_SEEDS: BuiltinSeed[] = [
  { slug: 'shield-check', label: 'Escudo verificado', category: 'seguridad' },
  { slug: 'trophy', label: 'Trofeo', category: 'general' },
  { slug: 'academic-cap', label: 'Graduación', category: 'educacion' },
  { slug: 'check-badge', label: 'Insignia verificada', category: 'seguridad' },
  { slug: 'star', label: 'Estrella', category: 'general' },
  { slug: 'heart', label: 'Corazón', category: 'general' },
  { slug: 'light-bulb', label: 'Idea', category: 'general' },
  { slug: 'sparkles', label: 'Destacado', category: 'general' },
  { slug: 'document', label: 'Documento', category: 'documentos' },
  { slug: 'clipboard', label: 'Portapapeles', category: 'documentos' },
  { slug: 'book', label: 'Libro', category: 'educacion' },
  { slug: 'newspaper', label: 'Noticias', category: 'documentos' },
  { slug: 'certificate', label: 'Certificado', category: 'documentos' },
  { slug: 'phone', label: 'Teléfono', category: 'comunicacion' },
  { slug: 'envelope', label: 'Correo', category: 'comunicacion' },
  { slug: 'chat', label: 'Chat', category: 'comunicacion' },
  { slug: 'bell', label: 'Campana', category: 'comunicacion' },
  { slug: 'computer', label: 'Computador', category: 'tecnologia' },
  { slug: 'computer-desktop', label: 'Escritorio', category: 'tecnologia' },
  { slug: 'device-mobile', label: 'Celular', category: 'tecnologia' },
  { slug: 'tablet', label: 'Tablet', category: 'tecnologia' },
  { slug: 'chart-bar', label: 'Gráfica', category: 'tecnologia' },
  { slug: 'presentation', label: 'Presentación', category: 'tecnologia' },
  { slug: 'qr-code', label: 'Código QR', category: 'tecnologia' },
  { slug: 'truck', label: 'Camión', category: 'transporte' },
  { slug: 'car', label: 'Automóvil', category: 'transporte' },
  { slug: 'bus', label: 'Bus', category: 'transporte' },
  { slug: 'bicycle', label: 'Motocicleta', category: 'transporte' },
  { slug: 'signal', label: 'Señal / tránsito', category: 'transporte' },
  { slug: 'map-pin', label: 'Ubicación', category: 'transporte' },
  { slug: 'globe', label: 'Mundo', category: 'transporte' },
  { slug: 'building', label: 'Edificio', category: 'general' },
  { slug: 'home', label: 'Inicio', category: 'general' },
  { slug: 'users', label: 'Usuarios', category: 'general' },
  { slug: 'user-group', label: 'Grupo', category: 'general' },
  { slug: 'user-circle', label: 'Usuario', category: 'general' },
  { slug: 'hand-raised', label: 'Mano levantada', category: 'general' },
  { slug: 'lifebuoy', label: 'Salvavidas', category: 'seguridad' },
  { slug: 'first-aid', label: 'Primeros auxilios', category: 'seguridad' },
  { slug: 'defensive', label: 'Conducción defensiva', category: 'seguridad' },
  { slug: 'exclamation', label: 'Advertencia', category: 'seguridad' },
  { slug: 'fire', label: 'Incendio', category: 'seguridad' },
  { slug: 'stop', label: 'Detener', category: 'seguridad' },
  { slug: 'eye', label: 'Visibilidad', category: 'seguridad' },
  { slug: 'wrench', label: 'Herramienta', category: 'tecnologia' },
  { slug: 'mechanic', label: 'Mecánica', category: 'tecnologia' },
  { slug: 'bolt', label: 'Energía', category: 'general' },
  { slug: 'sun', label: 'Sol', category: 'general' },
  { slug: 'flag', label: 'Bandera', category: 'general' },
  { slug: 'arrow-right', label: 'Flecha derecha', category: 'general' },
  { slug: 'check-circle', label: 'Verificado', category: 'general' },
  { slug: 'plus', label: 'Más', category: 'general' },
  { slug: 'minus', label: 'Menos', category: 'general' },
  { slug: 'magnifying-glass', label: 'Buscar', category: 'general' },
  { slug: 'trending-up', label: 'Tendencia', category: 'general' },
  { slug: 'download-tray', label: 'Descargar', category: 'general' },
  { slug: 'inbox', label: 'Bandeja', category: 'comunicacion' },
  { slug: 'identification', label: 'Identificación', category: 'documentos' },
  { slug: 'beaker', label: 'Laboratorio', category: 'educacion' },
  { slug: 'award', label: 'Premio', category: 'general' },
  { slug: 'target', label: 'Objetivo', category: 'general' },
  { slug: 'pqr', label: 'PQR', category: 'documentos' },
  { slug: 'suggestion', label: 'Sugerencia', category: 'comunicacion' },
  { slug: 'complaint', label: 'Queja', category: 'comunicacion' },
  { slug: 'petition', label: 'Petición', category: 'comunicacion' },
  { slug: 'compliment', label: 'Felicitación', category: 'comunicacion' },
];

export const PORTAL_BUILTIN_ICON_CATALOG: PortalIconCatalogItem[] = BUILTIN_SEEDS.map((seed) => ({
  id: `builtin:${seed.slug}`,
  slug: seed.slug,
  label: seed.label,
  category: seed.category,
  kind: 'builtin' as const,
  value: seed.slug,
  activo: true,
}));

export function portalIconPreviewGlyph(slug: string, kind?: string, value?: string): string {
  const raw = String(value ?? slug ?? '').trim();
  if (kind === 'emoji') return raw;
  if (kind === 'image') return '🖼️';
  if (kind === 'alias') return PORTAL_ICON_PREVIEW_EMOJI[raw] || '↪';
  if (PORTAL_ICON_PREVIEW_EMOJI[raw]) return PORTAL_ICON_PREVIEW_EMOJI[raw];
  if (/^\p{Extended_Pictographic}/u.test(raw)) return raw;
  return PORTAL_ICON_PREVIEW_EMOJI[slug] || '◆';
}
