import {
  heroAcademicCapSolid,
  heroArrowDownTraySolid,
  heroArrowRightSolid,
  heroArrowTrendingUpSolid,
  heroBeakerSolid,
  heroBellAlertSolid,
  heroBoltSolid,
  heroBookOpenSolid,
  heroBuildingLibrarySolid,
  heroChartBarSolid,
  heroChatBubbleLeftRightSolid,
  heroCheckBadgeSolid,
  heroCheckCircleSolid,
  heroClipboardDocumentCheckSolid,
  heroComputerDesktopSolid,
  heroDevicePhoneMobileSolid,
  heroDeviceTabletSolid,
  heroDocumentTextSolid,
  heroEnvelopeSolid,
  heroExclamationTriangleSolid,
  heroEyeSolid,
  heroFireSolid,
  heroFlagSolid,
  heroGlobeAltSolid,
  heroHandRaisedSolid,
  heroHeartSolid,
  heroHomeModernSolid,
  heroIdentificationSolid,
  heroInboxSolid,
  heroLifebuoySolid,
  heroLightBulbSolid,
  heroMagnifyingGlassSolid,
  heroMapPinSolid,
  heroMinusSmallSolid,
  heroNewspaperSolid,
  heroPhoneSolid,
  heroPlusSmallSolid,
  heroPresentationChartBarSolid,
  heroQrCodeSolid,
  heroShieldCheckSolid,
  heroSignalSolid,
  heroSparklesSolid,
  heroStarSolid,
  heroStopSolid,
  heroSunSolid,
  heroTrophySolid,
  heroTruckSolid,
  heroUserCircleSolid,
  heroUserGroupSolid,
  heroUsersSolid,
  heroWrenchScrewdriverSolid,
} from '@ng-icons/heroicons/solid';
import {
  bootstrapBicycle,
  bootstrapBusFrontFill,
  bootstrapCarFrontFill,
} from '@ng-icons/bootstrap-icons';

/** Iconos registrados globalmente (tree-shaking: solo los importados). */
export const PORTAL_ICON_SET = {
  heroAcademicCapSolid,
  heroArrowDownTraySolid,
  heroArrowRightSolid,
  heroArrowTrendingUpSolid,
  heroBeakerSolid,
  heroBellAlertSolid,
  heroBoltSolid,
  heroBookOpenSolid,
  heroBuildingLibrarySolid,
  heroChartBarSolid,
  heroChatBubbleLeftRightSolid,
  heroCheckBadgeSolid,
  heroCheckCircleSolid,
  heroClipboardDocumentCheckSolid,
  heroComputerDesktopSolid,
  heroDevicePhoneMobileSolid,
  heroDeviceTabletSolid,
  heroDocumentTextSolid,
  heroEnvelopeSolid,
  heroExclamationTriangleSolid,
  heroEyeSolid,
  heroFireSolid,
  heroFlagSolid,
  heroGlobeAltSolid,
  heroHandRaisedSolid,
  heroHeartSolid,
  heroHomeModernSolid,
  heroIdentificationSolid,
  heroInboxSolid,
  heroLifebuoySolid,
  heroLightBulbSolid,
  heroMagnifyingGlassSolid,
  heroMapPinSolid,
  heroMinusSmallSolid,
  heroNewspaperSolid,
  heroPhoneSolid,
  heroPlusSmallSolid,
  heroPresentationChartBarSolid,
  heroQrCodeSolid,
  heroShieldCheckSolid,
  heroSignalSolid,
  heroSparklesSolid,
  heroStarSolid,
  heroStopSolid,
  heroSunSolid,
  heroTrophySolid,
  heroTruckSolid,
  heroUserCircleSolid,
  heroUserGroupSolid,
  heroUsersSolid,
  heroWrenchScrewdriverSolid,
  bootstrapBicycle,
  bootstrapBusFrontFill,
  bootstrapCarFrontFill,
} as const;

/** Claves semánticas + emojis legacy (contenido ERP / defaults). */
const PORTAL_ICON_ALIASES: Record<string, keyof typeof PORTAL_ICON_SET> = {
  'academic-cap': 'heroAcademicCapSolid',
  phone: 'heroPhoneSolid',
  'map-pin': 'heroMapPinSolid',
  computer: 'heroComputerDesktopSolid',
  'chart-bar': 'heroChartBarSolid',
  'check-badge': 'heroCheckBadgeSolid',
  'device-mobile': 'heroDevicePhoneMobileSolid',
  'trending-up': 'heroArrowTrendingUpSolid',
  bicycle: 'bootstrapBicycle',
  car: 'bootstrapCarFrontFill',
  bus: 'bootstrapBusFrontFill',
  truck: 'heroTruckSolid',
  'shield-check': 'heroShieldCheckSolid',
  wrench: 'heroWrenchScrewdriverSolid',
  lifebuoy: 'heroLifebuoySolid',
  clipboard: 'heroClipboardDocumentCheckSolid',
  document: 'heroDocumentTextSolid',
  book: 'heroBookOpenSolid',
  bell: 'heroBellAlertSolid',
  trophy: 'heroTrophySolid',
  heart: 'heroHeartSolid',
  globe: 'heroGlobeAltSolid',
  building: 'heroBuildingLibrarySolid',
  envelope: 'heroEnvelopeSolid',
  chat: 'heroChatBubbleLeftRightSolid',
  star: 'heroStarSolid',
  'light-bulb': 'heroLightBulbSolid',
  exclamation: 'heroExclamationTriangleSolid',
  'magnifying-glass': 'heroMagnifyingGlassSolid',
  flag: 'heroFlagSolid',
  bolt: 'heroBoltSolid',
  eye: 'heroEyeSolid',
  'hand-raised': 'heroHandRaisedSolid',
  sun: 'heroSunSolid',
  signal: 'heroSignalSolid',
  users: 'heroUsersSolid',
  'user-circle': 'heroUserCircleSolid',
  'user-group': 'heroUserGroupSolid',
  presentation: 'heroPresentationChartBarSolid',
  newspaper: 'heroNewspaperSolid',
  'qr-code': 'heroQrCodeSolid',
  identification: 'heroIdentificationSolid',
  inbox: 'heroInboxSolid',
  tablet: 'heroDeviceTabletSolid',
  home: 'heroHomeModernSolid',
  beaker: 'heroBeakerSolid',
  fire: 'heroFireSolid',
  stop: 'heroStopSolid',
  minus: 'heroMinusSmallSolid',
  plus: 'heroPlusSmallSolid',
  'check-circle': 'heroCheckCircleSolid',
  'arrow-right': 'heroArrowRightSolid',
  'download-tray': 'heroArrowDownTraySolid',
  sparkles: 'heroSparklesSolid',
  android: 'heroDevicePhoneMobileSolid',
  download: 'heroArrowTrendingUpSolid',
  certificate: 'heroIdentificationSolid',
  award: 'heroTrophySolid',
  target: 'heroCheckCircleSolid',
  camp: 'heroSunSolid',
  visibility: 'heroEyeSolid',
  mechanic: 'heroWrenchScrewdriverSolid',
  defensive: 'heroShieldCheckSolid',
  'first-aid': 'heroLifebuoySolid',
  pqr: 'heroDocumentTextSolid',
  suggestion: 'heroLightBulbSolid',
  complaint: 'heroExclamationTriangleSolid',
  petition: 'heroBellAlertSolid',
  compliment: 'heroStarSolid',
  '🎓': 'heroAcademicCapSolid',
  '📞': 'heroPhoneSolid',
  '📍': 'heroMapPinSolid',
  '💻': 'heroComputerDesktopSolid',
  '📊': 'heroChartBarSolid',
  '✅': 'heroCheckBadgeSolid',
  '📱': 'heroDevicePhoneMobileSolid',
  '📈': 'heroArrowTrendingUpSolid',
  '🏍️': 'bootstrapBicycle',
  '🚗': 'bootstrapCarFrontFill',
  '🚌': 'bootstrapBusFrontFill',
  '🚛': 'heroTruckSolid',
  '🛡️': 'heroShieldCheckSolid',
  '🔧': 'heroWrenchScrewdriverSolid',
  '⛑️': 'heroLifebuoySolid',
  '📋': 'heroClipboardDocumentCheckSolid',
  '📜': 'heroDocumentTextSolid',
  '📚': 'heroBookOpenSolid',
  '🔔': 'heroBellAlertSolid',
  '🏅': 'heroTrophySolid',
  '✉️': 'heroEnvelopeSolid',
  '💬': 'heroChatBubbleLeftRightSolid',
  '🇨🇴': 'heroFlagSolid',
  '🛣️': 'heroGlobeAltSolid',
  '💛': 'heroHeartSolid',
  '💚': 'heroHeartSolid',
  '🏫': 'heroBuildingLibrarySolid',
  '⭐': 'heroStarSolid',
  '💡': 'heroLightBulbSolid',
  '⚠️': 'heroExclamationTriangleSolid',
  '🔍': 'heroMagnifyingGlassSolid',
  '👉': 'heroHandRaisedSolid',
  '💪': 'heroBoltSolid',
  '🚦': 'heroSignalSolid',
  '📄': 'heroDocumentTextSolid',
  '⛺': 'heroSunSolid',
  '👁️': 'heroEyeSolid',
  '🤝': 'heroUserGroupSolid',
  '🎯': 'heroCheckCircleSolid',
  '−': 'heroMinusSmallSolid',
  '+': 'heroPlusSmallSolid',
  '▣': 'heroQrCodeSolid',
  '✦': 'heroSparklesSolid',
};

export function resolvePortalIconName(raw: string | null | undefined): string | null {
  const value = String(raw ?? '').trim();
  if (!value) return null;

  if (value in PORTAL_ICON_SET) return value;

  const alias = PORTAL_ICON_ALIASES[value];
  if (alias) return alias;

  return 'heroSparklesSolid';
}

export const PORTAL_SECTION_ICON_KEYS: Record<string, string[]> = {
  valores: ['shield-check', 'star', 'users', 'academic-cap', 'heart', 'bolt'],
  testimonios: ['user-circle', 'building', 'academic-cap'],
  pasos: ['clipboard', 'book', 'check-badge', 'device-mobile', 'trophy'],
  carreras: ['shield-check', 'magnifying-glass', 'academic-cap', 'chart-bar', 'users'],
  acercaValores: ['star', 'globe', 'user-group', 'target', 'heart', 'car'],
};

export function portalSectionIcon(seccion: string, index: number): string {
  const list = PORTAL_SECTION_ICON_KEYS[seccion] ?? ['sparkles'];
  return list[Math.abs(index) % list.length];
}
